import Head from "next/head";
import { Box, Container, Typography, Button } from "@mui/material";
import Header from "@/shared/components/Header";
import Footer from "@/shared/components/Footer";

export function HomeContent() {
  return (
    <>
      {/* Hero Section */}
      <Box
        component="section"
        sx={{
          minHeight: "85vh",
          display: "flex",
          alignItems: "center",
          backgroundImage: 'url("/medico.png")',
          backgroundSize: "cover",
          backgroundPosition: "left top",
          backgroundRepeat: "no-repeat",
          position: "relative",
          pt: { xs: 12, md: 10 },
          pb: { xs: 6, md: 8 },
        }}
      >
        <Container maxWidth="lg" sx={{ position: "relative", zIndex: 2 }}>
          <Box
            sx={{
              maxWidth: "650px",
              ml: { xs: 2, md: "45%" },
              pr: { xs: 2, md: 4 },
            }}
          >
            <Typography
              variant="overline"
              sx={{
                fontWeight: 600,
                mb: 2,
                color: "#5FA8B0",
                letterSpacing: 2,
                fontSize: "0.85rem",
                display: "block",
              }}
            >
              AVALIAÇÃO E SAÚDE
            </Typography>
            <Typography
              variant="h2"
              sx={{
                fontWeight: 700,
                mb: 3,
                color: "#1E6B73",
                lineHeight: 1.2,
                fontSize: { xs: "2.5rem", md: "3.5rem" },
              }}
            >
              Instrumentos de Avaliação de Câncer de Pênis
            </Typography>
            <Typography
              sx={{
                mb: 5,
                color: "#5A6C7D",
                fontSize: { xs: "1rem", md: "1.15rem" },
                lineHeight: 1.6,
              }}
            >
              Ferramentas de avaliação para o diagnóstico de câncer de pênis
            </Typography>
            <Button
              variant="contained"
              href="/tela-avaliacao"
              sx={{
                bgcolor: "#00BCD4",
                color: "#FFF",
                borderRadius: 1.5,
                px: 5,
                py: 1.8,
                textTransform: "none",
                fontWeight: 600,
                fontSize: "1rem",
                boxShadow: "0 4px 12px rgba(0, 188, 212, 0.3)",
                "&:hover": {
                  bgcolor: "#00ACC1",
                  boxShadow: "0 6px 16px rgba(0, 188, 212, 0.4)",
                  transform: "translateY(-2px)",
                  transition: "all 0.3s ease",
                },
              }}
            >
              Saiba mais
            </Button>
          </Box>
        </Container>
      </Box>

      {/* Seção Informativa */}
      <Box
        component="section"
        sx={{
          py: { xs: 6, md: 10 },
          bgcolor: "#FFFFFF",
        }}
      >
        <Container maxWidth="lg">
          <Typography
            variant="h4"
            sx={{
              fontWeight: 700,
              mb: 4,
              color: "#1E6B73",
              lineHeight: 1.4,
            }}
          >
            O que é câncer de Pênis? Entenda a doença, seus sinais e a
            importância do diagnóstico precoce
          </Typography>
          <Typography
            variant="h6"
            sx={{
              fontWeight: 700,
              mb: 3,
              color: "#2C3E50",
              fontSize: "1.25rem",
            }}
          >
            Entenda o câncer de pênis
          </Typography>
          <Typography
            sx={{
              color: "#5A6C7D",
              lineHeight: 1.9,
              fontSize: "1.05rem",
              textAlign: "justify",
              pr: 2,
            }}
          >
            O câncer de pênis é uma doença rara que ocorre quando células
            malignas crescem na pele e nos tecidos do pênis. Ele inicia-se com
            células anormais que se multiplicam de forma descontrolada, podendo
            se espalhar para outras partes do corpo. O câncer mais comum do
            órgão é o carcinoma de células escamosas, que afeta mais de 95% dos
            casos. Entre as causas, estão fatores como falta de higiene,
            infecções por HPV (papilomavírus humano) e o hábito de fumar. A
            cirurgia de fimose e a realização da circuncisão diminuem o risco de
            desenvolver essa doença.
          </Typography>
        </Container>
      </Box>

    </>
  );
}

export default function Home() {
  return (
    <>
      <Head>
        <title>Prevenção Câncer de Pênis</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <HomeContent />
      <Footer />
    </>
  );
}
