import Head from "next/head";
import { Box, Container, Typography, Button } from "@mui/material";
import Grid from "@mui/material/Grid";
import Header from "@/components/Header/page";
import Footer from "@/components/Footer/page";

export default function Home() {
  return (
    <>
      <Head>
        <title>Prevenção Câncer de Pênis</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />

      {/* Conteúdo Principal */}
      <Box
        component="section"
        sx={{
          minHeight: "90vh",
          display: "flex",
          alignItems: "center",
          backgroundImage: 'url("/medico.png")',
          backgroundSize: "cover",
          backgroundPosition: "center",
          backgroundRepeat: "no-repeat",
          pt: 14,
          pb: { xs: 6, md: 12 },
        }}
      >
        <Container maxWidth="lg" sx={{ textAlign: "left" }}>
          <Box sx={{ maxWidth: 600 }}>
            <Typography
              variant="overline"
              sx={{ fontWeight: 600, mb: 1, color: "#47878E" }}
            >
              Avaliação e Saúde
            </Typography>

            <Typography
              variant="h4"
              sx={{ fontWeight: 700, mb: 3, color: "#1F6C75" }}
            >
              Instrumento de Avaliação de Câncer de Pênis
            </Typography>

            <Typography sx={{ mb: 4, color: "#454D5D" }}>
              Ferramentas de avaliação para o diagnóstico de câncer de pênis
            </Typography>

            <Button
              variant="contained"
              href="/avaliacao"
              sx={{
                bgcolor: "#0A6C74",
                borderRadius: 5,
                px: 4,
                py: 1.2,
                textTransform: "none",
                fontWeight: 500,
                "&:hover": { bgcolor: "#085A61" },
              }}
            >
              Saiba mais
            </Button>
          </Box>
        </Container>
      </Box>

      <Footer />
    </>
  );
}
